export default [
  "Abessinierkatze",
  "Abgottschlange",
  "Ablisaurus",
  "Adeliepinguin",
  "Adler",
  "Affe",
  "Affenpinscher",
  "Afghanischer Windhund",
  "Afrikanische Baumkröte",
  "Afrikanische Zibetkatze",
  "Afrikanischer Elefant",
  "Afrikanischer Strauß",
  "Afrikanischer Wildhund",
  "Aga-Kröte",
  "Aguti",
  "Ägyptische Mau",
  "Airedale Terrier",
  "Akbaş",
  "Akita",
  "Alaskan Malamute",
  "Albatros",
  "Aldabra-Riesenschildkröte",
  "Alligator",
  "Alpine Dachsbracke",
  "Altdeutscher Schäferhund",
  "Ameise",
  "Ameisenbär",
  "Ameisenigel",
  "Ameisenlöwe",
  "American Akita",
  "American Bulldog",
  "American Curl",
  "American Eskimo Dog",
  "American Foxhound",
  "American Pitbull Terrier",
  "American Shorthair",
  "American Staffordshire Terrier",
  "American Water Spaniel",
  "American Wirehair",
  "Amerikanische Schaufelfußkröte",
  "Amerikanischer Bison",
  "Amerikanischer Cocker Spaniel",
  "Amerikanischer Schwarzbär",
  "Amsel",
  "Anakonda",
  "Anatolischer Hirtenhund",
  "Anglerfisch",
  "Antilope",
  "Appenzeller Sennenhund",
  "Ara",
  "Arthropleura",
  "Asiatische Riesenhornisse",
  "Asiatische Tigermücke",
  "Asiatischer Elefant",
  "Asiatischer Löwe",
  "Atlantischer Ammenhai",
  "Auerhuhn",
  "Auerochse",
  "Austern",
  "Austernfischer",
  "Australian Cattle Dog",
  "Australian Kelpie",
  "Australian Mist",
  "Australian Shepherd",
  "Australian Stumpy Tail Cattle Dog",
  "Australian Terrier",
  "Australische Wasseragame",
  "Australischer Lungenfisch",
  "Axolotl",
  "Bachstelze",
  "Balinesenkatze",
  "Bänderroller",
  "Bandwurm",
  "Bär",
  "Barbe",
  "Barosaurus",
  "Barrakuda",
  "Bartagame",
  "Basenji",
  "Basset Hound",
  "Baumfrosch",
  "Baummarder",
  "Baumsteigerfrosch",
  "Bayerischer Gebirgshund",
  "Beagle",
  "Bearded Collie",
  "Bedlington Terrier",
  "Belgischer Schäferhund",
  "Bengalkatze",
  "Berger Picard",
  "Berggorilla",
  "Berner Sennenhund",
  "Bernhardiner",
  "Beutelmarder",
  "Beutelwolf",
  "Biber",
  "Biberratte",
  "Bichon Frisé",
  "Bienenfresser",
  "Bilche",
  "Binturong",
  "Birma-Katze",
  "Bisamratte",
  "Bison",
  "Black and Tan Coonhound",
  "Blässhuhn",
  "Blattlaus",
  "Blaumeise",
  "Blauwal",
  "Blindschleiche",
  "Blobfisch",
  "Bloodhound",
  "Blue Lacy",
  "Bluetick Coonhound",
  "Blutegel",
  "Bobtail",
  "Bologneser",
  "Bolonka-Zwetna",
  "Bombay-Katze",
  "Bongo",
  "Bordeauxdogge",
  "Border Collie",
  "Border Terrier",
  "Borneo-Orang-Utan",
  "Borneo-Zwergelefant",
  "Boston Terrier",
  "Boykin Spaniel",
  "Brachiosaurus",
  "Braunbär",
  "Breitmaulnashorn",
  "Brillenbär",
  "Brillenpinguin",
  "Broholmer",
  "Brückenechse",
  "Brüllaffe",
  "Buchfink",
  "Buckelwal",
  "Bullenhai",
  "Bullmastiff",
  "Bullterrier",
  "Buntbarsch",
  "Burma-Katze",
  "Ca de Bou",
  "Cairn Terrier",
  "Cane Corso Italiano",
  "Cão da Serra da Estrela",
  "Capybara",
  "Carolina Dog",
  "Cavalier King Charles Spaniel",
  "Ceratopsia",
  "Český fousek",
  "Chamäleon",
  "Chantilly-Tiffany",
  "Chausie",
  "Chesapeake Bay Retriever",
  "Chihuahua",
  "Chinchilla",
  "Chinesischer Schopfhund",
  "Chinook",
  "Chow-Chow",
  "Clownfisch",
  "Clumber Spaniel",
  "Collie",
  "Cross-River-Gorilla",
  "Curly Coated Retriever",
  "Dachs",
  "Dackel",
  "Dalmatiner",
  "Damagazelle",
  "Damhirsch",
  "Darwin-Nasenfrosch",
  "Deerhound",
  "Delfin",
  "Deutsche Bracke",
  "Deutsche Dogge",
  "Deutscher Boxer",
  "Deutscher Pinscher",
  "Deutscher Schäferhund",
  "Deutscher Wachtelhund",
  "Devon Rex",
  "Dikdiks",
  "Dilophosaurus",
  "Dingo",
  "Diplodocus",
  "Diskusfisch",
  "Distelfalter",
  "Dobermann",
  "Dodo",
  "Dogo Argentino",
  "Dogo Canario",
  "Dohle",
  "Doktorfisch",
  "Dompfaff",
  "Doppelfüßer",
  "Dornhai",
  "Dornteufel",
  "Dorsch",
  "Drever",
  "Drossel",
  "Dsungarischer Zwerghamster",
  "Dugong",
  "Dünengazelle",
  "Dunker",
  "Echse",
  "Echte Witwe",
  "Echter Leguan",
  "Eichelhäher",
  "Eichhörnchen",
  "Einsiedlerkrebs",
  "Eintagsfliege",
  "Eisbär",
  "Eistaucher",
  "Eisvogel",
  "Elch",
  "Elefant",
  "Elster",
  "Englische Bulldogge",
  "English Cocker Spaniel",
  "English Coonhound",
  "English Mastiff",
  "English Pointer",
  "English Setter",
  "English Shepherd",
  "English Springer Spaniel",
  "Ente",
  "Entlebucher Sennenhund",
  "Eoraptor",
  "Epagneul de Pont-Audemer",
  "Erdferkel",
  "Erdkröte",
  "Erdmännchen",
  "Esel",
  "Eselspinguin",
  "Europäischer Aal",
  "Falke",
  "Falsche Schwimmratte",
  "Falterfisch",
  "Färberfrosch",
  "Fasan",
  "Faultier",
  "Felsenpinguin",
  "Fennek",
  "Feuerfisch",
  "Feuerqualle",
  "Feuerwanze",
  "Field Spaniel",
  "Fila Brasileiro",
  "Filander",
  "Fingertier",
  "Finnischer Lapphund",
  "Finnischer Spitz",
  "Finnwal",
  "Fisch",
  "Fischertukan",
  "Fischkatze",
  "Flamingo",
  "Flat Coated Retriever",
  "Fleckenmusang",
  "Fledermaus",
  "Fliege",
  "Florfliege",
  "Flughörnchen",
  "Flunder",
  "Flussdelfin",
  "Flusspferd",
  "Fossa",
  "Foxterrier",
  "Französische Bulldogge",
  "Fregattvogel",
  "Frettchen",
  "Frosch",
  "Fuchs",
  "Galápagos-Pinguin",
  "Galapagos-Riesenschildkröte",
  "Gämse",
  "Gangesgavial",
  "Gans",
  "Garnele",
  "Gecko",
  "Geier",
  "Gelbaugenpinguin",
  "Geoffrey-Perückenaffe",
  "Gepard",
  "Gerippter Brachkäfer",
  "Gespenst-Plattschwanzgecko",
  "Gespenstschrecke",
  "Gibbon",
  "Gila-Krustenechse",
  "Giraffe",
  "Glasschleiche",
  "Gleithörnchen",
  "Glühwürmchen",
  "Gnu",
  "Goldammer",
  "Golden Retriever",
  "Goldenes Löwenäffchen",
  "Goldhamster",
  "Goldschopfpinguin",
  "Gordon Setter",
  "Gorilla",
  "Grabfrosch",
  "Grasfrosch",
  "Grauen Mausmaki",
  "Grauer Riffhai",
  "Greyhound",
  "Grizzlybär",
  "Grönlandhund",
  "Große Achatschnecke",
  "Große Anakonda",
  "Große Riesenmuschel",
  "Großer Ameisenbär",
  "Großer Barrakuda",
  "Großer Emu",
  "Großer Fetzenfisch",
  "Großer Gabelschwanz",
  "Großer Kudu",
  "Großer Panda",
  "Großer Schillerfalter",
  "Großer Schweizer Sennenhund",
  "Großzahnhai",
  "Grottenolm",
  "Guppy",
  "Gürtelmull",
  "Gürteltier",
  "Halsbandpekari",
  "Halsbandsittich",
  "Hammerhai",
  "Hamster",
  "Harpyie",
  "Harrier",
  "Hase",
  "Haubenpinguin",
  "Haushund",
  "Hauskatze",
  "Havaneser",
  "Hecht",
  "Heimchen",
  "Herkuleskäfer",
  "Hermelin",
  "Heuschrecke",
  "Himalayan",
  "Hirsch",
  "Hirschkäfer",
  "Hirschziegenantilope",
  "Hokkaido",
  "Holländischer Schäferhund",
  "Honigbiene",
  "Hornhai",
  "Hornisse",
  "Hovawart",
  "Huhn",
  "Humboldt-Pinguin",
  "Hummel",
  "Hummer",
  "Hund",
  "Hundertfüßer",
  "Husarenaffe",
  "Hyäne",
  "Ibis",
  "Igel",
  "Impala",
  "Indische Sternschildkröte",
  "Indischer Elefant",
  "Indisches Palmenhörnchen",
  "Indochinesischer Tiger",
  "Indri",
  "Inlandtaipan",
  "Insekten",
  "Irischer Wolfshund",
  "Irish Red Setter",
  "Irish Terrier",
  "Irish Water Spaniel",
  "Islandhund",
  "Jabiru",
  "Jack Russell Terrier",
  "Jagdelster",
  "Jagdspinne",
  "Jägerliest",
  "Jaguar",
  "Jaguarundi",
  "Jämthund",
  "Japan Chin",
  "Japan-Spitz",
  "Japanbrillenvogel",
  "Japanbuschsänger",
  "Japanisches Eichhörnchen",
  "Japanmakak",
  "Java-Nashorn",
  "Javaneraffe",
  "Javanese",
  "Jindo",
  "Jungferngecko",
  "Käfer",
  "Kaiman",
  "Kaiserpinguin",
  "Kaiserschnurrbarttamarin",
  "Kakadu",
  "Kakapo",
  "Kalifornische Gopherschildkröte",
  "Kalmar",
  "Kamel",
  "Kanaan-Hund",
  "Kanadischer Eskimohund",
  "Känguru",
  "Kaninchen",
  "Karakal",
  "Karelischer Bärenhund",
  "Karpfen",
  "Kasuar",
  "Katalanischer Schäferhund",
  "Kaukasischer Owtascharka",
  "Kegelrobbe",
  "Kentosaurus",
  "Kishu",
  "Kiwi",
  "Klammeraffe",
  "Klapperschlange",
  "Kleidermotte",
  "Kleiner Wasserfrosch",
  "Kleinpudel",
  "Klippschliefer",
  "Knochenhecht",
  "Koala",
  "Koboldmaki",
  "Kohlmeise",
  "Kojote",
  "Kolibri",
  "Komodowaran",
  "Kondor",
  "Königskrabbe",
  "Königspinguin",
  "Königspython",
  "Königstiger",
  "Koralle",
  "Kornnatter",
  "Krabbe",
  "Kragenbär",
  "Kragenechse",
  "Krallenfrosch",
  "Kranich",
  "Kroatischer Schäferhund",
  "Krokodil",
  "Krokodilteju",
  "Kronenpinguin",
  "Kugelfisch",
  "Kuh",
  "Kürbisspinne",
  "Kuskus",
  "Kuvasz",
  "Labradoodle",
  "Labrador-Retriever",
  "Lachs",
  "Lama",
  "Lämmergeier",
  "Landassel",
  "Landschildkröte",
  "Langhaarcollie",
  "Langhaariger Pyrenäenschäferhund",
  "Langohrigel",
  "Langschnabelsittich",
  "Lannerfalke",
  "Lanzenotter",
  "LaPerm",
  "Lappländischer Rentierhund",
  "Larvenroller",
  "Laubfalter",
  "Lebensmittelmotte",
  "Lederwanze",
  "Leistenkrokodil",
  "Lemming",
  "Lemur",
  "Leopard",
  "Lerche",
  "Leuchtqualle",
  "Libelle",
  "Liger",
  "Lippenbär",
  "Lippfisch",
  "Lisztaffe",
  "Löffelente",
  "Löwe",
  "Luchs",
  "Lykoi",
  "Magellan-Pinguin",
  "Maikäfer",
  "Maine-Coon-Katze",
  "Malaienbär",
  "Malaiische Zibetkatze",
  "Malaysia-Tiger",
  "Malteser",
  "Mammut",
  "Manchester-Terrier",
  "Mandrill",
  "Mangusten",
  "Mantarochen",
  "Marderhund",
  "Marienkäfer",
  "Mastiff",
  "Mastino Napoletano",
  "Maultier",
  "Maulwurf",
  "Maus",
  "Mäusebussard",
  "Mauswiesel",
  "Meeresnacktschnecke",
  "Meeresschildkröte",
  "Meerschweinchen",
  "Mensch",
  "Mexikanische Rotknie-Vogelspinne",
  "Miesmuschel",
  "Milben",
  "Miniature Bull Terrier",
  "Mistkäfer",
  "Monarchfalter",
  "Mönchsgrasmücke",
  "Mondfisch",
  "Monte-Iberia-Fröschchen",
  "Mops",
  "Motte",
  "Möwe",
  "Mudi",
  "Munchkin",
  "Mungo",
  "Muräne",
  "Murmeltier",
  "Nachtfalter",
  "Nachtigall",
  "Nacktmull",
  "Nandu",
  "Narwal",
  "Nasenaffe",
  "Nasenbär",
  "Nasenbeutler",
  "Nashorn",
  "Nashornkäfer",
  "Neandertaler",
  "Nebelparder",
  "Nerz",
  "Neufundländer",
  "Neunaugen",
  "Neuntöter",
  "Neuwelt-Sumpfschildkröte",
  "Nishikigoi",
  "Nordamerikanischer Ochsenfrosch",
  "Norfolk Terrier",
  "Norwegische Waldkatze",
  "Norwegischer Buhund",
  "Norwegischer Elchhund",
  "Norwegischer Lundehund",
  "Numbat",
  "Nymphensittich",
  "Ochse",
  "Ocicat",
  "Ohrwurm",
  "Okapi",
  "Oktopus (Kraken)",
  "Opossum",
  "Orang-Utan",
  "Oribi",
  "Östlicher Flachlandgorilla",
  "Östlicher Gorilla",
  "Ostsibirischer Laika",
  "Otter",
  "Otterhound",
  "Ozelot",
  "Panama-Kapuzineraffe",
  "Pantherschildkröte",
  "Panzernashorn",
  "Papagei",
  "Papageitaucher",
  "Paradiesvogel",
  "Pardelroller",
  "Parson Russell Terrier",
  "Patagotitan",
  "Pavian",
  "Pekinese",
  "Pelikan",
  "Perlhuhn",
  "Perserkatze",
  "Peruanischer Nackthund",
  "Pfau",
  "Pfeilschwanzkrebse",
  "Pferd",
  "Pfirsichköpfchen",
  "Pharaonenhund",
  "Pika",
  "Pinguin",
  "Piranha",
  "Pirol",
  "Plesiosaurus",
  "Plumploris",
  "Podenco Ibicenco",
  "Polarfuchs",
  "Polarhase",
  "Polarwolf",
  "Polnische Bracke",
  "Polnischer Niederungshütehund",
  "Portugiesischer Wasserhund",
  "Possum",
  "Pottwal",
  "Pteranodon",
  "Pudel",
  "Pudelpointer",
  "Puma",
  "Pyrenäen-Berghund",
  "Pyrenäen-Mastiff",
  "Qualle",
  "Quappe",
  "Quastenflosser",
  "Querzahnmolche",
  "Quetzal",
  "Quittenwaran",
  "Quokka",
  "Rabe",
  "Ragdoll-Katze",
  "Rankenfußkrebs",
  "Ratte",
  "Rauchschwalbe",
  "Raufußhühner",
  "Raupe",
  "Regenbogenforelle",
  "Regenwurm",
  "Reiher",
  "Rennmaus",
  "Rentier",
  "Rhesusaffe",
  "Rhodesian Ridgeback",
  "Riesenbiber",
  "Riesenfaultier",
  "Riesenhai",
  "Riesenschnauzer",
  "Ringelnatter",
  "Robbe",
  "Rochen",
  "Rosalöffler",
  "Rosenkäfer",
  "Rotbarsch",
  "Rote Mordwanze",
  "Rote Waldameise",
  "Roter Panda",
  "Rothandtamarin",
  "Rothund",
  "Rotkehlchen",
  "Rotluchs",
  "Rotmilan",
  "Rottweiler",
  "Rotwolf",
  "Rundschwanzseekuh",
  "Rüsselspringer",
  "Russisch Blau",
  "Russischer Schwarzer Terrier",
  "Saarlooswolfhund",
  "Saatkrähe",
  "Säbelschnäbler",
  "Säbelzahntiger",
  "Salamander",
  "Saluki",
  "Saola",
  "Sardelle",
  "Schabe",
  "Schaf",
  "Schakal",
  "Schimpanse",
  "Schipperke",
  "Schirmvogel",
  "Schlange",
  "Schleie",
  "Schleiereule",
  "Schlupfwespe",
  "Schmetterling",
  "Schmuck-Hornfrosch",
  "Schnabeltier",
  "Schnappschildkröte",
  "Schnauzer",
  "Schnecke",
  "Schneeeule",
  "Scholle",
  "Schottisches Hochlandrind",
  "Schraubenziege",
  "Schrimps",
  "Schwamm",
  "Schwan",
  "Schwarzdelfin",
  "Schwarzer Panther",
  "Schwedischer Vallhund",
  "Schwein",
  "Schwertwal",
  "Scottish Fold",
  "Scottish Terrier",
  "Seeelefant",
  "Seefrosch",
  "Seegurke",
  "Seeigel",
  "Seeleopard",
  "Seelöwe",
  "Seeohren",
  "Seeotter",
  "Seepferdchen",
  "Seescheiden",
  "Seeskorpion",
  "Seestern",
  "Segelflosser",
  "Seidenraupen",
  "Selkirk Rex",
  "Sepien",
  "Serval",
  "Shar-Pei",
  "Shetland Sheepdog",
  "Shiba Inu",
  "Shih Tzu",
  "Shikoku",
  "Siamesischer Kampffisch",
  "Siamkatze",
  "Siberian Husky",
  "Sibirische Katze",
  "Sibirischer Tiger",
  "Siebenschläfer",
  "Silberdollar",
  "Silberfischchen",
  "Singdrossel",
  "Skorpion",
  "Skorpionfisch",
  "Smaragdspint",
  "Snowshoe",
  "Somali-Katze",
  "Spanischer Mastiff",
  "Spanischer Wasserhund",
  "Spatz",
  "Specht",
  "Spinne",
  "Spinosaurus",
  "Spitzmaulkärpfling",
  "Spitzmaulnashorn",
  "Springbock",
  "Sri-Lanka-Elefant",
  "Stachelrochen",
  "Stachelschwein",
  "Staffordshire Bullterrier",
  "Stegosaurus",
  "Steinbock",
  "Steinbutt",
  "Steinkauz",
  "Stellers Seekuh",
  "Sternflecksalmler",
  "Stieglitz",
  "Stinktier",
  "Stör",
  "Storch",
  "Strahlenschildkröte",
  "Strauß",
  "Streifenhörnchen",
  "Striped Rocket Frosch",
  "Südchinesischer Tiger",
  "Südliche Grünmeerkatze",
  "Südliche Seebären",
  "Sumatra-Elefant",
  "Sumatra-Nashorn",
  "Sumatra-Orang-Utan",
  "Sumatra-Tiger",
  "Sumpfkrokodil",
  "Sussex Spaniel",
  "Tapanuli-Orang-Utan",
  "Tapir",
  "Taschenratte",
  "Tasmanischer Teufel",
  "Taube",
  "Taubenschwänzchen",
  "Tausendfüßler",
  "Teddyhamster",
  "Teichfrosch",
  "Teichmolch",
  "Teichrallen",
  "Termiten",
  "Terrier Brasileiro",
  "Terrorvogel",
  "Tetra",
  "Thai Ridgeback",
  "Thaikatze",
  "Thunfisch",
  "Tibet Spaniel",
  "Tibet Terrier",
  "Tibetdogge",
  "Tiffanie-Katze",
  "Tiger",
  "Tigerhai",
  "Tigersalamander",
  "Tintenfisch",
  "Tölpel",
  "Tosa Inu",
  "Totenkopfaffe",
  "Trampeltier",
  "Tropikvogel",
  "Truthahn",
  "Tschechoslowakischer Wolfshund",
  "Tukan",
  "Tümmler",
  "Türkisch Angora",
  "Türkisch Van",
  "Tyrannosaurus Rex",
  "Uakari",
  "Uhu",
  "Unke",
  "Urzeitkrebs",
  "Utahraptor",
  "Vampirfledermaus",
  "Vari",
  "Vasapapagei",
  "Veilchenente",
  "Velociraptor",
  "Vielfraß",
  "Viper",
  "Vogel",
  "Vogelspinne",
  "Vulkanelfe",
  "Vulkankaninchen",
  "Vulkanohrwurm",
  "Wachtel",
  "Waldelefant",
  "Waldkauz",
  "Waldohreule",
  "Walhai",
  "Wallaby",
  "Walross",
  "Wanderdrossel",
  "Waran",
  "Warzenschwein",
  "Waschbär",
  "Wasserbüffel",
  "Wasserläufer",
  "Wasserratte",
  "Wasserspinne",
  "Wattwurm",
  "Weberknecht",
  "Weinbergschnecke",
  "Weißer Hai",
  "Weißer Tiger",
  "Weißkopfseeadler",
  "Wellensittich",
  "Welsartige",
  "Welsh Corgi",
  "Welsh Corgi Cardigan",
  "Welsh Springer Spaniel",
  "Welsh Terrier",
  "Wespe",
  "Wespenspinne",
  "West Highland White Terrier",
  "Westlicher Flachlandgorilla",
  "Westlicher Gorilla",
  "Whippet",
  "Wiesel",
  "Wildschwein",
  "Winkelspinne",
  "Wisent",
  "Wolf",
  "Wollaffe",
  "Wollhaarmammut",
  "Wombat",
  "Wüstenrennmaus",
  "Yak",
  "Yeti-Krabbe",
  "Yorkshire Terrier",
  "Zander",
  "Zauneidechse",
  "Zaunkönig",
  "Zebra",
  "Zebrafink",
  "Zebrahai",
  "Zebramanguste",
  "Zebroide",
  "Zebu",
  "Zecke",
  "Ziege",
  "Zigeunerhuhn",
  "Zikade",
  "Zilpzalp",
  "Zipfelfrosch",
  "Zitteraal",
  "Zitterspinne",
  "Zobel",
  "Zorse",
  "Zügeldelfin",
  "Zügelpinguin",
  "Zweifarbentamarin",
  "Zwergadler",
  "Zwergalk",
  "Zwergflusspferd",
  "Zwergpinguin",
  "Zwergpinscher",
  "Zwergpudel",
  "Zwergschimpanse",
  "Zwergschnauzer",
  "Zwergseidenäffchen",
  "Zwergspitze",
  "Zwergwal",
];
