import desisAnimals from "./animals";

export default {
  einleitung: [
    "Sorry Jungs",
    "Tut mir leid Mädels",
    "Oops",
    "Oh...",
    "Ach je",
    "Sorry, hab die Nachricht jetzt erst gelesen",
    "Sorry Jungs, kann heute nicht",
    "Shit...",
    "Oh mein Gott",
  ],
  entschuldigung: [
    "ich hab völlig verpennt",
    "ich hab verschwitzt",
    "mir ist entfallen",
    "ich hab nicht bedacht",
    "ich hab völlig vergessen",
    "mir war nicht klar",
    "mir ist dazwischen gekommen",
    "ich hab verpeilt",
  ],
  ausrede: [
    ...desisAnimals.map(animal => `Desi's ${animal} gestorben ist`),
    "ich morgen Fotoshooting mit der Family hab",
    "eine meiner 5.000 Nichten morgen getauft wird",
    "meine Oma zum fünften mal in diesem Jahr gestorben ist",
    "morgen Heilige drei Könige ist und wir das immer feiern",
    "mein Auto keinen Sprit mehr hat",
    "mein Auto nicht angesprungen ist",
    "mein Vater mir mein Auto nicht gegeben hat",
    "morgen der Jahrestag von Desi's totem Hamster ist",
    "morgen der Jahrestag von Desi's totem Kaninchen ist",
    "morgen der Jahrestag von Desi's totem Meerschweinchen ist",
    "ich meine Tage habe",
    "ich mit den Jungs in Schottland Röcke anprobieren bin",
    "Desi's Hamster einen Zahn gezogen bekommen hat",
    "ich mir beim Anstehen vor der Disco die Bänder gerissen hab",
    "ich dein Handy meinem Neffen geschenkt habe",
    "mein neugekauftes und von meinem Schwager generalüberholtes Auto zum dritten Mal in dieser Woche in der Werkstatt ist",
    "mein Auspuff schon wieder abgefallen ist. Dabei steht Peugeot doch für echte französische Wertarbeit",
    "ich übrigens doch nicht zu meinem eigenen Geburtstag kommen kann. Kann mir das feiern doch nicht leisten. Die Geschenke könnt ihr mir ja bei Gelegenheit geben",
    "ich doch nicht zum Fußball kommen kann. Mir ist aufgefallen dass ich mich dafür bewegen müsste. Das ist mir nach einem anstrengenden Tag World of Warcraft zu viel",
    "Fußball doch heute nichts wird. Hab grade gemerkt dass Ich zu fett dafür bin",
    "ich 9 Millionen für Gbamin geboten habe. Ich wollte nur 990.000 bieten! Aber ihr könnt mir ja sicher mein Geld zurück geben. Ansonsten kann ich leider nicht kommen, weil ich jetzt pleite bin",
    "ich heute doch nicht The Walking Dead gucken kommen kann. Desi will lieber was lebensbejahendes schauen. Aber sie sagt dass sie die Serie sehr interessant findet",
    "heut gar keine Postkutsche mehr fährt. Das ist jetzt blöd",
    "ich mir den Urlaub ja doch gar nicht leisten kann. Gut, dass mir das einen Tag vor Abreise noch eingefallen ist",
    "ich meinem vierjährigen Neffen versprochen habe heute in Texas Chainsaw Massace zu gehen",
    "ich mit meiner Schwester zum All-You-can-eat-Buffet gehen wollte",
    "meine Schwester Hilfe beim Einkaufen braucht. Sie kann das ganze Schwein nicht allein tragen",
    "mein mega sicherer E-Sport ETF leider 2000% Miese gemacht hat",
    "ich leider meine ganze Kohle bei der Währungsspekulation verloren habe. Dabei klangen afrikanische Dollar so sicher",
    "ich meine Brille leider im Pool verloren habe",
    "ich euch leider doch nicht zum Fußball schauen einladen kann. Ich war ja erst 30 mal bei euch",
  ],
  vertroestung: [
    "Aber das nächste mal bin ich auf jeden Fall am Start",
    "Aber wir sehen uns ja nächste Woche",
    "Aber das passiert sicher nicht nochmal",
    "Sorry, das konnte ich aber echt vorher nicht wissen",
    "Sorry, aber dafür kann ich wirklich nichts",
    "Nächstes mal bin ich auf jeden Fall dabei",
    "Jetzt ist es leider zu spät",
    "Es gibt ja noch andere Tage",
    "Wir sind ja noch jung",
  ],
};
